# Combined Peering + NS-3 CSMA Scenario
# This scenario uses:
# - 4-node peering topology from docker-compose.yml
# - NS-3 TAP-CSMA layer connection for network simulation
#
# The nodes communicate through the NS-3 simulated CSMA network

services:
  # NS-3 Network Simulator - must start first
  ns_3:
    image: "ns3-lena"
    build:
      dockerfile: images/ns-3.Dockerfile
      context: .
    container_name: ns-3
    network_mode: "host"
    volumes:
      - ./src/tap-csma-scenario.cc:/usr/local/ns-allinone-3.37/ns-3.37/scratch/tap-csma-scenario.cc
    tty: true
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun

  # Peering nodes connected via NS-3 simulated network
  node-1:
    container_name: node-1
    build:
      context: .
      dockerfile: images/pynode.Dockerfile
    network_mode: "none"  # No Docker networking - uses NS-3 TAP bridge
    tty: true
    depends_on:
      - ns_3
    command:
      - "--peers=10.0.0.2:5000,10.0.0.3:5000,10.0.0.4:5000"

  node-2:
    container_name: node-2
    build:
      context: .
      dockerfile: images/pynode.Dockerfile
    network_mode: "none"
    tty: true
    depends_on:
      - ns_3
      - node-1
    command:
      - "--peers=10.0.0.1:5000,10.0.0.3:5000,10.0.0.4:5000"

  node-3:
    container_name: node-3
    build:
      context: .
      dockerfile: images/pynode.Dockerfile
    network_mode: "none"
    tty: true
    depends_on:
      - ns_3
      - node-2
    command:
      - "--peers=10.0.0.1:5000,10.0.0.2:5000,10.0.0.4:5000"

  node-4:
    container_name: node-4
    build:
      context: .
      dockerfile: images/pynode.Dockerfile
    network_mode: "none"
    tty: true
    depends_on:
      - ns_3
      - node-3
    command:
      - "--peers=10.0.0.1:5000,10.0.0.2:5000,10.0.0.3:5000"
